version: "3.8"

services:
  pharmacy:
    container_name: pharmacy-container
    build:
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    depends_on:
      - postgres_db
    environment:
      DB_USER: pharmacy_user
      DB_NAME: pharmacy
      DB_PASSWORD: postgres
      DB_HOST: postgres_db
      DB_PORT: 5432
  postgres_db:
    image: postgres:latest
    container_name: postgres-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: pharmacy_user
      POSTGRES_DB: pharmacy
    volumes:
     - pg_data:/var/lib/postgresql/data
volumes:
  pg_data: {}



