db_username: postgres
db_password: EDGG3gD-2b*f5D434G4fCbDDG-23fB*2
db_uriName: railway

spring:
  data:
    redis:
      host: redis-18964.c281.us-east-1-2.ec2.cloud.redislabs.com
      port: 18964
      password: Fs2l5kn3oMIeJadkbRGC93N0mZbs9DCB
      username: default
   #   url: jdbc:redis://monorail.proxy.rlwy.net:21991/0
  mail:
    host: smtp.gmail.com
    port: 587
    username: yvycvydfgg@gmail.com
    password: jvrlucfxwbeevdnp
    properties:
      mail.smtp.starttls.enable: true
      mjaail.smtp.auth: true
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${db_username}
    password: ${db_password}
    url: jdbc:postgresql://monorail.proxy.rlwy.net:10806/${db_uriName}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
jwt:
  expiry: 30000000
  secret: asdfghjkl;'';lkjhgfdsaqwertyuiop[[poiuytrewqzxcvbnm,.,mnbvcxz
server:
  port: 9090